name: cjb
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  firebase_messaging: ^15.0.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  awesome_notifications: ^0.9.3+1
  google_fonts: ^6.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/picture_placeholder.jpeg
    - assets/logo.jpg
    - assets/logo_icon.png
    - assets/bg_image_1.jpeg
    - assets/bg_image_2.png
    - assets/bg_image_3.jpeg
    - assets/celebrate.png
    - assets/curious.png
    - assets/google_logo_svg.svg
    - assets/insightful.png
    - assets/holder.jpeg
    - assets/love.png
    - assets/on_boarding_1.jpg
    - assets/on_boarding_2.jpg
    - assets/on_boarding_3.jpg
    - assets/post_image_1.jpg
    - assets/post_image_g.jpg
    - assets/post_image_2.jpg
    - assets/post_image_3.jpg
    - assets/post_image_5.jpg
    - assets/profile_1.jpeg
    - assets/profile_2.jpeg
    - assets/thumbs_up.png
    - assets/service-account-file.json
